### ISSUE TITLE
how to start the bot with polygon mainnet

### ISSUE THREAD

**Issue by pamarthisai** [0x1ea/aave-liquidation-bot#1]
hi wonderfull programme how to start this with polygon mainnet

**Comment by 0x1ea** [comment]
You have to update some files before execute the `libot.js` script.

**first:**
Create an `.env` file with all the variables. use `.env.example` as reference

**second:**
Update the `scripts/libot.js` file with your configuration:
```js
// ....
const CHAIN = "polygon";
const PUBLIC_PROVIDER_URL = config.rpcUrl[CHAIN].public;
const PROVIDER_URL = config.rpcUrl[CHAIN].local;     // you can change local (forked blockchain) for: 'public', 'infura' or 'alchemy'
const MY_ACCOUNT = config.keys.private;              // access at your private key at the .env file
// ...
```

**third:**
now you can run the `libot.js` script

**Comment by pamarthisai** [comment]
command : node libot.js is or node libot.js --network polygon

**Comment by 0x1ea** [comment]
the first one: node scripts/libot.js

**Comment by pamarthisai** [comment]
thank you so much for ur greate response and finaly searching for polygon is printed and my last doubt is user data is refreshing automaticly or we have to update?

**Comment by 0x1ea** [comment]
to update users data run `refreshUserDataV2.js` script whenever you want, but it is not 100% necessary. 

To deploy the contract just run `deployZap.js` after update:
```js
const CHAIN = "polygon";  // previously "mainnet"
const MY_ACCOUNT = config.keys.private; // previously 'fake'
const PROVIDER_URL = config.rpcUrl[CHAIN].local; // local for a forked blockchain, alchemy or infura

```

**Comment by pamarthisai** [comment]
const CHAIN = "polygon";  // previously "mainnet"
const MY_ACCOUNT = config.keys.private; // previously 'fake'
const PROVIDER_URL = config.rpcUrl[CHAIN].local; // local for a forked blockchain, alchemy or infura


but 

reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}

**Comment by 0x1ea** [comment]
Are you running a forked polygon mainnet?
if not, change 'local' (config.rpcUrl[CHAIN].**local**) for infura or alchemy. Remember create/update the .env file with your full rpcUrl + api key

**Comment by pamarthisai** [comment]
yeah iam trying on mainnet like (config.rpcUrl[CHAIN].local;) but network not detected but with same .env libot.js are running sucussfully

**Comment by 0x1ea** [comment]
I don't know why you still get this error if you are running a local blockchain forked from polygon mainnet at at "http://127.0.0.1:8545/". Try to hardcode your rpcurl on line 17 of the deploy script, from "process.env.[whatever]" to "https://your_rpc_provider/your_api_key"
